import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Providers } from "@/shared/providers/providers";

const font = Open_Sans({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={clsx(
          `antialiased`,
          font.variable,
          "bg-black overflow-hidden"
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
